image: python:3.8

before_script:
  - pip install mkdocs
  - pip install mkdocs-material
  - pip install markdown-include

pages:
  script:
    - mkdocs build
    - mv site public
  artifacts:
    paths:
      - public
  only:
    - master
