image: python:3.8

variables:
  GIT_DEPTH: 1000

before_script:
  - pip install mkdocs mkdocs-material markdown-include mkdocs-git-revision-date-localized-plugin

pages:
  script:
    - mkdocs build
    - mv site public
  artifacts:
    paths:
      - public
  only:
    - master
