image: python:3.8

before_script:
  - pip install mkdocs
  - pip install mkdocs-material
  - pip install markdown-include
  - pip3 install mkdocs-git-revision-date-localized-plugin

pages:
  script:
    - mkdocs build
    - mv site public
  artifacts:
    paths:
      - public
  only:
    - master

variables:
  GIT_DEPTH: 1000

clone:
  depth: full

steps:
  - uses: actions/checkout@v2
    with:
      fetch-depth: 0
