image: python:3.8

variables:
  GIT_DEPTH: 1000

before_script:
  - pip install mkdocs mkdocs-material mkdocs-git-revision-date-localized-plugin mike
  - mike install-extras 
  - mike deploy 0.1.0 latest  
  - mike set-default latest

pages:
  script:
    - mkdocs build
    - mv site public
  artifacts:
    paths:
      - public
  only:
    - master

