site_name: Astecas | Documentação

#Repositório GitLab
repo_url: https://gitlab.com/marcela-fernanda/documentacao-astecas
repo_name: astecas/documentacao
edit_uri: ""

nav:
  - Sobre:
      - O que é o Astecas?: index.md
  - Getting Started:
      - Instalação: getting-started.md
      - Processos: getting-started/processos.md
  - Esquemas de dados:
      - Esquema Astecas: databases/db-astecas.md
      - Esquema Admin: databases/db-admin.md
      - Esquema BAAS: databases/db-baas.md
  - Changelog:
      - Releases: changelog.md

theme:
    name: 'material'
    logo: assets/images/logo.png
    favicon: assets/images/logo-color.png
    features:
      - navigation.tabs
    language: pt
    palette:
        scheme: astecas
    icon:
        repo: fontawesome/brands/gitlab

extra_css:
  - stylesheets/extra.css
  - stylesheets/version-select.css

extra_javascript:
  - javascripts/extra.js
  - javascripts/version-select.js

markdown_extensions:
  - toc:
        permalink: true
  - admonition
  - pymdownx.details
  - pymdownx.tabbed
  - pymdownx.superfences
  - abbr
  - pymdownx.snippets
  - def_list
  - attr_list
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde

plugins:
  - search:
        lang:
          - pt
  - git-revision-date-localized
